### ISSUE TITLE
Parsing of NIXD0003 incorrect

### ISSUE THREAD

**Issue by deiruch** [i4Ds/STIX-data-center#5]
NIXD0003 is specified as having a width of 8 bits. The viewer shows values way above 255 for NIXD0003:

![image](https://user-images.githubusercontent.com/4119188/69417930-ed9c2c00-0d19-11ea-8dfa-1bea3a0e88ca.png)

Perhaps there's something wrong with the parsing/extraction?

(And, btw: FANTASTIC WORK! Great & very useful viewer!)

**Comment by deiruch** [comment]
@drhlxiao Have you had time to look at this?

**Comment by drhlxiao** [comment]
The parser did not process the unaligned byte correctly 
The bug has been fixed.
